# .travis.yml
language:    # 指明使用的语言
  - go 

go:          # 语言版本号
  - "1.11.5"   # 默认使用最新版本,注意，需要 "1.10" 版本的时候必须表示为字符串形式，如果写成 1.10 则会使用 1.1 版本;x表示对应前缀的最新版本

install:
- go get github.com/mattn/goveralls
- go get gopkg.in/check.v1
- go get github.com/golang/protobuf/proto
- go get github.com/stretchr/testify/assert

script:      # 执行的脚步，但是go默认会执行下面的这些命令的，所以可以不用写
- cd subdir
# see here: https://docs.travis-ci.com/user/common-build-problems/
#- travis_wait 30 go test -v -covermode=count -coverprofile=coverage.out -timeout=30m # see here: https://docs.travis-ci.com/user/common-build-problems/
#- pwd
#- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
- travis_wait 30 go test -v 
